ever-co/ever-demand

merchant/tablet-ionic/src/@shared/user/mutation/user-mutation.component.ts
=> feat(ever-merchant): create/edit customer with default image EV-1177

carrier/mobile-ionic/package.json, carrier/mobile-ionic/yarn.lock, merchant/tablet-ionic/package.json, merchant/tablet-ionic/yarn.lock, shop/mobile-ionic/package-lock.json, shop/mobile-ionic/package.json
=> Greenkeeper/default/@angular/pwa 0.13.7

carrier/mobile-ionic/package.json, merchant/tablet-ionic/package.json, merchant/tablet-ionic/yarn.lock, shop/mobile-ionic/package-lock.json, shop/mobile-ionic/package.json
=> Greenkeeper/default/@angular devkit/architect 0.13.7

shop/website-angular/package.json
=> chore(package): update @ngtools/webpack to version 7.3.7

backend/api/package.json, backend/api/yarn.lock
=> Greenkeeper/default/kafka node 4.0.4

backend/api/src/services/services.app.ts
=> feat(ever-api): show messages when generate https certificates EV-980

backend/api/package.json, backend/api/yarn.lock, carrier/mobile-ionic/package.json, carrier/mobile-ionic/yarn.lock, merchant/tablet-ionic/package.json, merchant/tablet-ionic/yarn.lock
=> Greenkeeper/default/mongoose 5.5.0

backend/api/src/graphql/subscriptions/subscription.providers.ts
=> fix(ever-api): stopped subscription server listening

merchant/tablet-ionic/src/pages/+carriers/add-carriers-popup/add-new-carrier/location/location-form.component.ts
Carriers page EV-1212
---
Added feature for load initial (default) "Geolocation" data in the form for create new Carrier from Merchant app.
=> feat(ever-merchant): loaded initial Geolocation data when create carrier

backend/api/package.json, backend/api/yarn.lock
=> Greenkeeper/default/mongodb memory server 5.0.2

admin/website-angular/src/app/@core/auth/admin-auth-strategy.service.ts
=> Feature/ev 1217/logout redirection

carrier/mobile-ionic/package.json, carrier/mobile-ionic/yarn.lock, merchant/tablet-ionic/package.json, merchant/tablet-ionic/yarn.lock, shop/mobile-ionic/package-lock.json, shop/mobile-ionic/package.json
=> Greenkeeper/default/@ionic native/barcode scanner 5.5.1

carrier/mobile-ionic/package.json, carrier/mobile-ionic/yarn.lock, merchant/tablet-ionic/package.json, merchant/tablet-ionic/yarn.lock, shop/mobile-ionic/package-lock.json, shop/mobile-ionic/package.json
=> Greenkeeper/default/@ionic native/geolocation 5.5.1

carrier/mobile-ionic/package.json, carrier/mobile-ionic/yarn.lock, merchant/tablet-ionic/package.json, merchant/tablet-ionic/yarn.lock, shop/mobile-ionic/package-lock.json, shop/mobile-ionic/package.json
=> Greenkeeper/default/@ionic native/google analytics 5.5.1

carrier/mobile-ionic/package.json, carrier/mobile-ionic/yarn.lock, merchant/tablet-ionic/package.json, merchant/tablet-ionic/yarn.lock, shop/mobile-ionic/package-lock.json, shop/mobile-ionic/package.json
=> Greenkeeper/default/@ionic native/in app browser 5.5.1

carrier/mobile-ionic/package.json, carrier/mobile-ionic/yarn.lock, merchant/tablet-ionic/package.json, merchant/tablet-ionic/yarn.lock, shop/mobile-ionic/package-lock.json, shop/mobile-ionic/package.json
=> Greenkeeper/default/@ionic native/vibration 5.5.1

admin/website-angular/src/app/@shared/product/categories/categories-table/categories-table.component.html, admin/website-angular/src/app/@shared/warehouse/forms/basic-info/basic-info-form.component.html, admin/website-angular/src/app/@shared/warehouse/warehouse-mutation/warehouse-mutation.component.html, admin/website-angular/src/app/@theme/styles/styles.scss, admin/website-angular/src/app/pages/+carriers/track/carrier-tracking/carrier-tracking.component.html, admin/website-angular/src/app/pages/+dashboard/dashboard.component.ts, admin/website-angular/src/assets/i18n/bg.json, admin/website-angular/src/assets/i18n/en.json, admin/website-angular/src/assets/i18n/he.json, admin/website-angular/src/assets/i18n/ru.json
=> Feature ev 1218 test the platform

admin/website-angular/src/app/pages/+carriers/carriers.component.html, admin/website-angular/src/app/pages/+carriers/track/carrier-tracking/carrier-tracking.component.html, admin/website-angular/src/assets/i18n/bg.json, admin/website-angular/src/assets/i18n/en.json, admin/website-angular/src/assets/i18n/he.json, admin/website-angular/src/assets/i18n/ru.json
=> feat(ever-admin): add translate EV-1224

shop/mobile-ionic/src/app/pages/+products/products.page.ts
---
Fixed error which appears when switching the delivery type on Shop Mobile App.
=> fix(ever-shop-mobile): fixed error on switch the delivery type

admin/website-angular/src/app/@shared/render-component/name-redirect/name-redirect.component.html, admin/website-angular/src/app/@shared/user/ban-confirm/ban-confirm.component.html, admin/website-angular/src/app/pages/+customers/customers.component.html, admin/website-angular/src/app/pages/+customers/customers.component.ts
=> feat(ever-admin): improved ban feature

backend/api/src/services/users/UsersService.ts
=> feat(ever-admin): generate all in fake data now generates banned users

shop/website-angular/src/app/+orders/location/carrier-location.component.html, shop/website-angular/src/app/+orders/location/carrier-location.component.scss, shop/website-angular/src/app/+orders/location/carrier-location.component.ts, shop/website-angular/src/app/+orders/order/order.component.html, shop/website-angular/src/app/+orders/order/order.component.scss, shop/website-angular/src/app/+orders/order/order.component.ts, shop/website-angular/src/app/+orders/orders.component.html, shop/website-angular/src/app/+orders/orders.component.scss, shop/website-angular/src/app/+orders/orders.container.component.ts, shop/website-angular/src/app/+orders/orders.module.ts, shop/website-angular/src/styles/styles.scss
=> feat(ever-shop-web): fixed text overlap

admin/website-angular/src/app/@shared/payment-gateways/payPal-gateway/payPal-gateway.component.ts, admin/website-angular/src/app/@shared/payment-gateways/payment-gateways.component.html, admin/website-angular/src/app/@shared/payment-gateways/payment-gateways.component.ts, admin/website-angular/src/app/@shared/payment-gateways/stripe-gateway/stripe-gateway.component.ts, admin/website-angular/src/app/@shared/warehouse/forms/payments-settings/payments-settings-form.component.html, admin/website-angular/src/app/@shared/warehouse/forms/payments-settings/payments-settings-form.component.ts, admin/website-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/warehouse-manage-tabs.component.html
---
Improvements to Merchant Payments Settings
=> feat(ever-admin): complete manage "Merchant" payments settings EV-1231

shop/mobile-ionic/src/app/pages/+invite/+by-location/by-location.page.ts
---
Now if ARCGIS_CLIENT_ID and ARCGIS_CLIENT_SECRET are not provided on the server .env file, customer app will just get location from Google geocoder.
=> feat(ever-shop-mobile): improved get location on customer mobile

admin/website-angular/src/app/@shared/payment-gateways/payPal-gateway/payPal-gateway.component.ts, admin/website-angular/src/app/@shared/payment-gateways/stripe-gateway/stripe-gateway.component.ts, merchant/tablet-ionic/package.json, merchant/tablet-ionic/src/components/components.module.ts, merchant/tablet-ionic/src/components/confirm-delete-popup/confirm-delete-popup.html, merchant/tablet-ionic/src/components/confirm-delete-popup/confirm-delete-popup.ts, merchant/tablet-ionic/src/components/file-uploader/file-uploader.component.html, merchant/tablet-ionic/src/components/file-uploader/file-uploader.component.ts, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/mutation/mutation.html, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/mutation/mutation.scss, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/mutation/mutation.ts, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/payPal/payPal.html, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/payPal/payPal.scss, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/payPal/payPal.ts, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/payments.html, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/payments.scss, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/payments.ts, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/stripe/stripe.html, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/stripe/stripe.scss, merchant/tablet-ionic/src/components/settings-page-components/settings/payments/stripe/stripe.ts, merchant/tablet-ionic/src/components/settings-page-components/settings/settings.html, merchant/tablet-ionic/src/components/settings-page-components/settings/settings.module.ts, merchant/tablet-ionic/src/components/settings-page-components/settings/settings.scss, merchant/tablet-ionic/src/components/settings-page-components/settings/settings.ts, merchant/tablet-ionic/src/global.scss, merchant/tablet-ionic/src/pages/+settings/settings.module.ts, merchant/tablet-ionic/src/services/currencies.service.ts, merchant/tablet-ionic/yarn.lock, shared/core/enums/PaymentGateways.ts
=> feat(ever-merchant): init payments settings component

shop/mobile-ionic/src/assets/i18n/en-US.json
=> fix: in main menu "Legals" section renamed to "Legal"

backend/api/src/graphql/carriers/carrier.resolver.ts, backend/api/src/graphql/carriers/carriers.types.graphql, backend/api/src/graphql/users/user.resolver.ts, backend/api/src/graphql/users/users.types.graphql, backend/api/src/services/carriers/CarriersService.ts
=> fix: make sure mutations for updateEmail named differently

admin/website-angular/src/assets/i18n/es.json, carrier/mobile-ionic/src/assets/i18n/es.json, merchant/tablet-ionic/src/assets/i18n/es.json, shop/mobile-ionic/src/assets/i18n/es-ES.json, shop/website-angular/src/assets/i18n/es.json
We create Spanish Translations for labels of all Views
=> Spanish Translations

admin/website-angular/src/app/pages/+products/+product/product.component.html, admin/website-angular/src/app/pages/+products/+product/product.component.scss, admin/website-angular/src/app/pages/+products/+product/product.component.ts
---
Added location back functionality in selected product page!
=> feat: added back button on selected product page

admin/website-angular/src/app/pages/+warehouses/+warehouse-track/warehouse-track.component.html, admin/website-angular/src/app/pages/+warehouses/+warehouse/warehouse.component.ts, admin/website-angular/src/app/pages/+warehouses/warehouses.component.html, admin/website-angular/src/assets/i18n/bg-BG.json, admin/website-angular/src/assets/i18n/en-US.json, admin/website-angular/src/assets/i18n/es-ES.json, admin/website-angular/src/assets/i18n/fr.json, admin/website-angular/src/assets/i18n/he-IL.json, admin/website-angular/src/assets/i18n/ru-RU.json
-   [ x] Have you followed the [contributing guidelines](https://github.com/ever-co/ever/blob/master/.github/CONTRIBUTING.md)?
-   [x ] Have you explained what your changes do, and why they add value?
**Added translations**
=> Feat#1036/admin translations

backend/api/src/graphql/geo-locations/orders/geo-location-orders.resolver.ts, backend/api/src/graphql/geo-locations/orders/geo-locations-orders.graphql, backend/api/src/services/geo-locations/GeoLocationsOrdersService.ts, carrier/mobile-ionic/src/pages/main/delivery/delivery.html, carrier/mobile-ionic/src/pages/main/delivery/delivery.ts, carrier/mobile-ionic/src/pages/main/drive-to-warehouse/drive-to-warehouse.html, carrier/mobile-ionic/src/pages/main/drive-to-warehouse/drive-to-warehouse.ts, carrier/mobile-ionic/src/pages/main/home/home.ts, carrier/mobile-ionic/src/pages/main/main.html, carrier/mobile-ionic/src/pages/main/main.module.ts, carrier/mobile-ionic/src/pages/main/main.ts, carrier/mobile-ionic/src/pages/main/starting-delivery/starting-delivery.html, carrier/mobile-ionic/src/pages/main/starting-delivery/starting-delivery.ts, carrier/mobile-ionic/src/pages/product/get-product/get-product.html, carrier/mobile-ionic/src/pages/product/get-product/get-product.module.ts, carrier/mobile-ionic/src/pages/product/get-product/get-product.ts, carrier/mobile-ionic/src/pages/product/return-product/return-product.html, carrier/mobile-ionic/src/pages/product/return-product/return-product.ts, carrier/mobile-ionic/src/services/geo-location-order.service.ts, carrier/mobile-ionic/src/services/store.service.ts
=> Feature/cancel order carrier app#1030

admin/website-angular/src/app/pages/+products/+product/product-edit/product-edit.component.html, admin/website-angular/src/app/pages/+products/+product/product-edit/product-edit.component.ts
---
In selected store, on product edit page added back button click to redirect to previous directory.
=> fix: fixed on back button to go to previous directory

shop/mobile-ionic/src/app/pages/+merchants/merchants.page.html, shop/mobile-ionic/src/assets/i18n/en-US.json, shop/mobile-ionic/src/assets/i18n/es-ES.json
---
Fixed language change translations from english to spanish in mobile shop stores for placeholder and search result message!
=> fix: language translation in mobile shop

admin/website-angular/src/app/@shared/warehouse/forms/basic-info/basic-info-form.component.html, admin/website-angular/src/app/@shared/warehouse/forms/basic-info/basic-info-form.component.ts, admin/website-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/details/warehouse-manage-tabs-details.component.html, admin/website-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/details/warehouse-manage-tabs-details.component.ts, backend/api/src/graphql/warehouses/warehouses.types.graphql, shared/core/entities/Warehouse.ts, shared/core/interfaces/IWarehouse.ts
---
See a little demo https://www.screencast.com/t/VH7PsqSo
=> Feature/merchant carriers #1029

packages/core/webpack.config.js
=> Fix core webpack build

shop/mobile-ionic/src/app/pages/+products/+order/common/payment/payment.component.ts
=> fix: send correct order id on Payment with Stage

packages/merchant-tablet-ionic/src/assets/i18n/bg-BG.json, packages/merchant-tablet-ionic/src/assets/i18n/bg.json, packages/merchant-tablet-ionic/src/assets/i18n/en-US.json, packages/merchant-tablet-ionic/src/assets/i18n/en.json, packages/merchant-tablet-ionic/src/assets/i18n/es-ES.json, packages/merchant-tablet-ionic/src/assets/i18n/he-IL.json, packages/merchant-tablet-ionic/src/assets/i18n/he.json, packages/merchant-tablet-ionic/src/assets/i18n/ru-RU.json, packages/merchant-tablet-ionic/src/assets/i18n/ru.json, packages/merchant-tablet-ionic/src/components/order/make-order/make-order.component.ts
---
New order popup message translation.
=> feat: new order popup translation

packages/merchant-tablet-ionic/src/assets/i18n/es-ES.json
---
Fixed new client address field translation.
=> fix: fixed new client address translation

packages/merchant-tablet-ionic/src/pages/+language/language.html
---
Fixed not working change language functionality.
=> fix: fixed not working change language functionality

packages/admin-web-angular/src/app/pages/+warehouses/+warehouse/+warehouse-manage/warehouse-manage.component.ts
---
Used async/await as a temporary fix
=> fix: #1086 merchant data

packages/admin-web-angular/src/app/pages/+warehouses/+warehouse/+warehouse-manage/warehouse-manage.component.html, packages/admin-web-angular/src/app/pages/+warehouses/+warehouse/+warehouse-manage/warehouse-manage.component.ts
Fixed the UI to show save button if the selected warehouse is !null
=> fix: #1086 fix store ui

packages/admin-web-angular/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
---
Create new user on Admin Web gives error as debounceTime nedded to be wrapped in pipe.
https://www.loom.com/share/7f78c2faf51046ec9c9ed39c3c922da1
=> fix: create user popup debounceTime error

packages/admin-web-angular/src/app/pages/+customers/+customer/+customer-edit/customer-edit.component.ts
---
Edit customer throws two TypeError which I handled by wrapping the withLatestFrom in a pipe and by catching Error and completing the observable!
=> fix: edit customer throws an error

packages/admin-web-angular/src/app/pages/+dashboard/charts-panel/chart-panel-header/chart-panel-header.component.ts
---
Fixed error on admin dashboard when trying to create custom period. I red about this type of issue and according to angular documenation the problem may be that the component isnt present before change detection runs, so I changed static property to false!
https://www.loom.com/share/ac9a6bfdd09040fbbcce0f014ed3291b
=> fix: admin dashboard custom period throws an error

packages/admin-web-angular/src/app/pages/+warehouses/+warehouse-track/warehouse-track.component.html, packages/admin-web-angular/src/app/pages/+warehouses/+warehouse-track/warehouse-track.component.scss, packages/admin-web-angular/src/app/pages/+warehouses/+warehouse-track/warehouse-track.component.ts
---
Added back button on Stores -> Show on map page!
https://www.loom.com/share/17a4354249cc4f189d27be0f2e669326
=> fix: back btn on show on map page

packages/admin-web-angular/src/app/pages/+carriers/+carrier/carrier-orders/carrier-orders.component.ts
---
Finaly manage to handle error when trying to view carrier info and deliveries! For some reason all pipes with takeUntil(ngDestroy) trhew an Error and I decided to use a workaround by using subscription from which I am unsubscribing in ngOnDestroy() function! Tried to investigate what may cause the problem with takeUntil and got nowhere, but now everything seems to work fine!
=> fix: view carrier info and deliveries error

packages/admin-web-angular/src/app/pages/+profile/edit/account/account.component.ts, packages/admin-web-angular/src/app/pages/+profile/edit/basic-info/basic-info.component.ts
---
Fiexd error on admin profile page that blocked the whole view!
=> fix: view admin profile page error

packages/admin-web-angular/src/app/pages/+carriers/+carrier/+carrier-edit/carrier-edit.component.html, packages/admin-web-angular/src/app/pages/+carriers/+carrier/+carrier-edit/carrier-edit.component.ts
---
Fixed error whe trying to edit/view carrier's basic info!
=> fix: edit carrier throws error

packages/admin-web-angular/src/app/pages/+orders/+order/order.component.ts, packages/admin-web-angular/src/app/pages/+simulation/order/order.component.html, packages/admin-web-angular/src/app/pages/+warehouses/+warehouse/warehouse-order-view/warehouse-order-view.component.html
=> fix: comment out ng-simple-slideshow

packages/admin-web-angular/src/app/@core/data/warehouseOrders.service.ts, packages/admin-web-angular/src/app/pages/+warehouses/+warehouse/+warehouse-order/warehouse-order.component.ts
---
Fixed error on Stores -> Orders -> Create new order!
https://www.loom.com/share/0cd7c12e2c4f4bccbaf55c2cb6e43c04
=> fix: create new order error

packages/shop-web-angular/src/app/+orders/order/order.component.html, packages/shop-web-angular/src/app/+products/products.component.html, packages/shop-web-angular/src/assets/i18n/bg-BG.json, packages/shop-web-angular/src/assets/i18n/en-US.json, packages/shop-web-angular/src/assets/i18n/es-ES.json, packages/shop-web-angular/src/assets/i18n/he-IL.json, packages/shop-web-angular/src/assets/i18n/ru-RU.json
---
Fixed ShopWeb json placeholders not shown properly.
https://www.loom.com/share/21f67fc082e74649a63671485144dd84
=> fix: json values not displayed properly

packages/admin-web-angular/src/app/@theme/styles/everdark.theme.scss, packages/admin-web-angular/src/app/@theme/styles/everlight.theme.scss, packages/admin-web-angular/src/app/pages/+warehouses/warehouses.component.html
---
On custom EverLight and EverDark themes added  new primary color which took from Nebular default options. On EverLight removed primary to be #888 as we already have that color in info  option. On EverDark replaced primary #888 with #3366ff and called it primary without removing the $gray option from the top if we decide to get it back.
https://www.loom.com/share/f1f85f5055814066baaf2c904500153c
=> feat: made show on map button blue

packages/admin-web-angular/src/app/pages/+warehouses/warehouses.module.ts
---
Fixed wizard component to be recognized.
=> fix: made wizard component working

packages/admin-web-angular/package.json, packages/admin-web-angular/src/app/@shared/warehouse/forms/payments-settings/payments-settings-form.component.html, packages/admin-web-angular/src/app/@shared/warehouse/forms/payments-settings/payments-settings-form.component.ts, packages/admin-web-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/warehouse-manage-tabs.component.ts, packages/admin-web-angular/src/app/@shared/warehouse/warehouse-mutation/warehouse-mutation.component.ts, packages/admin-web-angular/src/app/pages/+setup/+merchants/components/payments/payments.component.html, packages/admin-web-angular/src/app/pages/+setup/+merchants/components/payments/payments.component.ts, packages/admin-web-angular/src/app/pages/+setup/+merchants/merchants.component.ts, packages/admin-web-angular/src/assets/i18n/bg-BG.json, packages/admin-web-angular/src/assets/i18n/bg.json, packages/admin-web-angular/src/assets/i18n/en-US.json, packages/admin-web-angular/src/assets/i18n/en.json, packages/admin-web-angular/src/assets/i18n/es-ES.json, packages/admin-web-angular/src/assets/i18n/he-IL.json, packages/admin-web-angular/src/assets/i18n/he.json, packages/admin-web-angular/src/assets/i18n/ru-RU.json, packages/admin-web-angular/src/assets/i18n/ru.json, packages/common/package.json, packages/common/src/entities/Warehouse.ts, packages/common/src/interfaces/IWarehouse.ts, packages/core/package.json
Need to make the interaction with the merchant
=> feat: added flag for cash payment

packages/common/src/entities/GeoLocation.ts
-   [ x] Have you followed the [contributing guidelines](https://github.com/ever-co/ever/blob/master/.github/CONTRIBUTING.md)?
-   [ x] Have you explained what your changes do, and why they add value?
--- sorted countries
=> fix: #1137-order-countries

packages/admin-web-angular/src/app/pages/+customers/+customer/+customer-edit/customer-edit.component.html, packages/admin-web-angular/src/app/pages/+customers/+customer/+customer-edit/customer-edit.component.ts
---
issue #1134 
https://www.loom.com/share/67c2e89af6ab46f9aa8616749c5b80f6
=> fix:#1134 connect the selected customer to the edit page

packages/merchant-tablet-ionic/src/assets/i18n/bg-BG.json, packages/merchant-tablet-ionic/src/assets/i18n/bg.json, packages/merchant-tablet-ionic/src/assets/i18n/en-US.json, packages/merchant-tablet-ionic/src/assets/i18n/en.json, packages/merchant-tablet-ionic/src/assets/i18n/es-ES.json, packages/merchant-tablet-ionic/src/assets/i18n/he-IL.json, packages/merchant-tablet-ionic/src/assets/i18n/he.json, packages/merchant-tablet-ionic/src/assets/i18n/ru-RU.json, packages/merchant-tablet-ionic/src/assets/i18n/ru.json, packages/merchant-tablet-ionic/src/components/common/order-info/order-info.html, packages/merchant-tablet-ionic/src/components/common/order-info/order-info.scss, packages/merchant-tablet-ionic/src/components/common/order-info/order-info.ts, packages/merchant-tablet-ionic/src/components/components.module.ts, packages/merchant-tablet-ionic/src/components/order-with-carrier/order-with-carrier.html, packages/merchant-tablet-ionic/src/components/order-without-carrier/order-without-carrier.html
---
Made order type appear on merchant orders.
=> feat: show order type on merchant

packages/carrier-mobile-ionic/src/components/order-card/order/product/product.component.html, packages/carrier-mobile-ionic/src/components/order-card/order/product/product.component.ts
-   [ x] Have you followed the [contributing guidelines](https://github.com/ever-co/ever/blob/master/.github/CONTRIBUTING.md)?
-   [x ] Have you explained what your changes do, and why they add value?
The logic in the function for getting the product images doesn't cover the case when product has translations neither for the current selected language nor english .. and the page breaks.
=> fix: #1147 carrier deliveries page image fix

packages/merchant-tablet-ionic/src/@shared/user/mutation/user-mutation.component.ts
---
Fixed error on Merchant create new customer.
https://www.loom.com/share/7e3899cde6cd4b31af68336ec786be41
=> fix: merchant new customer error

packages/carrier-mobile-ionic/angular.json, packages/carrier-mobile-ionic/src/components/menu/menu.component.html
=> fix: carrier menu icons not showing

packages/admin-web-angular/package.json, packages/admin-web-angular/src/app/pages/+fakeData/fakeData.component.ts
=> feat: added currency uyu

packages/shop-mobile-ionic/angular.json, packages/shop-mobile-ionic/src/app/components/menu/menu.component.html
---
On Mobile Shop fixed menu icons to appear as expected.
=> fix: shopmobile menu icons error

packages/merchant-tablet-ionic/src/components/file-uploader/file-uploader.component.html
-   [x ] Have you followed the [contributing guidelines](https://github.com/ever-co/ever/blob/master/.github/CONTRIBUTING.md)?
-   [x ] Have you explained what your changes do, and why they add value?
=> fix: #1180 carrier image field

packages/admin-web-angular/src/app/@shared/forms/location/location-form.component.ts, packages/shop-web-angular/src/app/+login/byLocation/location/location.component.ts
-   [ x] Have you followed the [contributing guidelines](https://github.com/ever-co/ever/blob/master/.github/CONTRIBUTING.md)?
-   [ x] Have you explained what your changes do, and why they add value?
**Countries order again.**
=> fix: #1181 admin register carrier countries order

packages/admin-web-angular/src/app/@shared/render-component/product-takeaway-delivery/product-takeaway-delivery.component.ts, packages/admin-web-angular/src/app/@shared/render-component/render-components.module.ts, packages/admin-web-angular/src/app/@shared/warehouse-product/forms/warehouse-products-table/warehouse-products-table.component.ts
---
Refactored Admin -> Stores -> Store -> Products -> Delivery/Takeaway type to look better.
https://www.loom.com/share/bf44af733e044695aade912dcca2fcb3
=> fix: refactored product delivery or takeaway

packages/carrier-mobile-ionic/src/pages/main/drive-to-warehouse/drive-to-warehouse.html, packages/carrier-mobile-ionic/src/pages/main/drive-to-warehouse/drive-to-warehouse.scss, packages/carrier-mobile-ionic/src/pages/main/drive-to-warehouse/drive-to-warehouse.ts
---
Made Order ID visible on Carrier.
=> feat: show order ID on carrier

packages/admin-web-angular/src/app/pages/+warehouses/+warehouse/+warehouse-manage/warehouse-manage.component.ts
---
Fixed cash payment option to be editable from Manage Store panel.
https://www.loom.com/share/6d0b1a03e97741a6b39c7b1803710df0
=> fix: cash payment not editable

packages/core/src/graphql/admin/admin.resolver.ts
=> feat: admin password change restriction #1097

packages/admin-web-angular/src/app/@shared/warehouse-product/forms/add-warehouse-products-table/add-warehouse-products-table.component.ts
---
issue: https://github.com/ever-co/ever/issues/1200
https://www.loom.com/share/5e0095030d18430b8e64dbd8e7ef4042
=> fix: admin / store / add product / fixing takeaway checkbox

packages/admin-web-angular/src/app/@shared/product/forms/basic-info/basic-info-form.component.html, packages/admin-web-angular/src/app/@shared/product/forms/basic-info/basic-info-form.component.ts, packages/common/src/interfaces/ILanguage.ts, packages/merchant-tablet-ionic/src/pages/+promotions/promotion-forms/basic-info/basic-info-form.component.html, packages/merchant-tablet-ionic/src/pages/+promotions/promotion-forms/basic-info/basic-info-form.component.ts
=> fix: add language enum

packages/admin-web-angular/package.json, packages/merchant-tablet-ionic/src/components/order/make-order/make-order.component.ts
Removed pop up related to this ticket
https://github.com/ever-co/ever/issues/1046
=> fix: removed unnecessary pop up

packages/core/src/graphql/warehouses-orders/warehouses-orders.types.graphql, packages/merchant-tablet-ionic/src/components/common/order-info/order-info.ts, packages/merchant-tablet-ionic/src/components/order/choose-customer-option.component.ts, packages/merchant-tablet-ionic/src/components/order/make-order/make-order.component.ts, packages/merchant-tablet-ionic/src/components/order/order-type/order-type.component.html, packages/merchant-tablet-ionic/src/components/order/order-type/order-type.component.scss, packages/merchant-tablet-ionic/src/components/order/order-type/order-type.component.ts, packages/merchant-tablet-ionic/src/components/order/order.component.html, packages/merchant-tablet-ionic/src/components/order/order.component.ts, packages/merchant-tablet-ionic/src/components/order/order.module.ts
---
Added option to New manual Order in Merchant for order to be ready for Takeaway or Delivery.
https://www.loom.com/share/dc92802d3a534c6eac6f2225c6031be4
=> feat: choose order type on new manual order

packages/admin-web-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/warehouse-manage-tabs.component.ts
---
Removed two checkes for Saving new store data on Admin Manage Store panel as in this.form.valid we are already checking if the contact form info is correct and removed isCashPaymentEnabled as there is nothing to validate it is either true or false and because it blocks every other form change to be validated separately.
Provided a video for preview!
https://www.loom.com/share/3aaf126d06734a81ab79608517ae7ec9
=> fix: activate save btn on valid form changes

packages/shop-mobile-ionic/src/app/pages/+products/products.page.ts
https://www.loom.com/share/bb7a5780404a4d30ad70b56b3bc2d12a
=> fix: when switching warehouse products weren't showing now they do

packages/shop-web-angular/src/app/+orders/order/order.component.ts, packages/shop-web-angular/src/app/+orders/orders.container.component.ts
---
Issue: https://github.com/ever-co/ever/issues/1206
*Added message if orders list is empty
In the video, you can figure out that now the view is updating immediately after receiving the data. Also, you can figure it when the cancel button blinking on order status changing.
https://www.loom.com/share/0ca8f3f432804579ae39e25440b7ede8
=> fix: orders and status not updating immediately

packages/admin-web-angular/src/app/@shared/render-component/store-product-is-available-checkbox/is-available-checkbox.component.ts, packages/merchant-tablet-ionic/package.json, packages/merchant-tablet-ionic/src/assets/i18n/bg-BG.json, packages/merchant-tablet-ionic/src/assets/i18n/bg.json, packages/merchant-tablet-ionic/src/assets/i18n/en-US.json, packages/merchant-tablet-ionic/src/assets/i18n/en.json, packages/merchant-tablet-ionic/src/assets/i18n/es-ES.json, packages/merchant-tablet-ionic/src/assets/i18n/he-IL.json, packages/merchant-tablet-ionic/src/assets/i18n/he.json, packages/merchant-tablet-ionic/src/assets/i18n/ru-RU.json, packages/merchant-tablet-ionic/src/assets/i18n/ru.json, packages/merchant-tablet-ionic/src/pages/+warehouse/edit-product-type-popup/edit-product-type-popup.html, packages/merchant-tablet-ionic/src/pages/+warehouse/edit-product-type-popup/edit-product-type-popup.ts
=> feat: impl prod unavailable func in merchant

packages/carrier-mobile-ionic/package.json, packages/carrier-mobile-ionic/src/pages/information/terms-of-use/terms-of-use.ts, packages/common-angular/src/routers/user-router.service.ts, packages/core/package.json, packages/core/src/services/users/UsersService.ts, packages/merchant-tablet-ionic/package.json, packages/merchant-tablet-ionic/src/pages/+info/+terms-of-use/terms-of-use.ts, packages/shop-mobile-ionic/package.json, packages/shop-mobile-ionic/src/app/pages/+info/+terms-of-use/terms-of-use.page.html, packages/shop-mobile-ionic/src/app/pages/+info/+terms-of-use/terms-of-use.page.ts, packages/shop-web-angular/src/app/+orders/orders.container.component.ts
So there is a problem with getting the build path.
=> feat: added new functionality for getting terms from db

packages/admin-web-angular/src/app/pages/+orders/+order/order-products/order-products.component.html, packages/admin-web-angular/src/assets/i18n/bg-BG.json, packages/admin-web-angular/src/assets/i18n/bg.json, packages/admin-web-angular/src/assets/i18n/en-US.json, packages/admin-web-angular/src/assets/i18n/en.json, packages/admin-web-angular/src/assets/i18n/es-ES.json, packages/admin-web-angular/src/assets/i18n/he-IL.json, packages/admin-web-angular/src/assets/i18n/he.json, packages/admin-web-angular/src/assets/i18n/ru-RU.json, packages/admin-web-angular/src/assets/i18n/ru.json
=> fix: misspelled word

packages/shop-mobile-ionic/src/app/pages/+products/+searchProducts/searchProducts.component.html, packages/shop-mobile-ionic/src/app/pages/+products/+searchProducts/searchProducts.component.ts
---
https://github.com/ever-co/ever/issues/806
https://www.loom.com/share/d70ea61c071347c7a44bdf9b212805a3
@evereq 
What exactly needs to show inside the single result field (merchant and product)
Merchants result are in gray (i think it can be better styled) and limited to 5
Products are in white fields and limited to 20 
Do we need a new switcher for takeaway/delivery?
In this case, I use the switcher above ... 
**!! this switcher affect only products result** …
=> feat: mobileshop search for products and merchants

packages/admin-web-angular/src/app/pages/+carriers/+carrier/carrier.component.ts
---
Fixed error on Admin -> Carriers -> Carrier change status Working/Not working
https://www.loom.com/share/3ba677e05c3a438c9bbfdbe57430fda3
=> fix: carrier change status error

packages/admin-web-angular/src/app/@shared/render-component/product-takeaway-delivery/product-takeaway-delivery.component.ts, packages/admin-web-angular/src/app/@shared/warehouse-product/forms/warehouse-products-table/warehouse-products-table.component.ts, packages/common-angular/package.json, packages/common-angular/src/routers/warehouse-products-router.service.ts, packages/core/package.json, packages/core/src/services/warehouses/WarehousesProductsService.ts
https://www.loom.com/share/4e3188031f8f4e8ca6eace4f4ec04883
There is one bug when you get the alert that you must have been selected at least one type, it still unticks it not sure how to deal with that yet, other thing maybe it shouldn't be just alert maybe we can use other kind of pop up
=> feat: implemented editing in admin panel

packages/shop-mobile-ionic/src/app/pages/+orders-history/orders-history.page.html
---
Fixed showing default view on Mobile shop when there are no orders made.
https://www.loom.com/share/8700fabb4cc7402ca5ef72fbdc7abdc0
=> fix: show no orders view on mobile shop

packages/admin-web-angular/package.json, packages/admin-web-angular/src/app/@core/data/geo-location.service.ts
---
Fixed showing only available products on manage customer section.
https://www.loom.com/share/4054c0bf3af04e82b6ae2d02b5d00a04
=> fix: show available products on customer panel

packages/core/package.json, packages/core/src/services/users/UsersProductsService.ts
---
Fixed error on Mobile Shop when navigating to Products panel!
https://www.loom.com/share/d6a9ec60636544758c34bab5eaed2ffe
=> fix: mobile shop error when viewing products

packages/admin-web-angular/src/app/pages/+warehouses/+warehouse/warehouse.component.ts, packages/common-angular/package.json, packages/common-angular/src/routers/warehouse-router.service.ts, packages/core/package.json, packages/core/src/services/warehouses/WarehousesService.ts
---
Fixed when set to inactive store's orders and products to be still visible from admin panel!
https://www.loom.com/share/3e22677a8e004fd2aa6223365aa40847
=> fix: when inactive show store orders and products

packages/admin-web-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/delivery-areas/warehouse-manage-tabs-delivery-areas.component.html, packages/admin-web-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/delivery-areas/warehouse-manage-tabs-delivery-areas.component.scss, packages/admin-web-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/delivery-areas/warehouse-manage-tabs-delivery-areas.component.ts, packages/admin-web-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/warehouse-manage-tabs.component.ts
---
https://www.loom.com/share/59f8adf876524495b2b65a3ca827d546
For now, just added a field in the DB with a delivery radius which can be controlled from warehouse's settings page
!! It is not replaced yet with the hardcoded 50000m 
**not sure is that the best place in warehouse's settings to add this controller 
@evereq
=> feat: add maximum delivery radius settings

packages/common/package.json, packages/common/src/entities/GeoLocation.ts
---
Fixed error on Admin ->Carrier
https://www.loom.com/share/9c7e4ddd466c4889a2a811a44a1ee602
=> fix: error admin view carrier

packages/carrier-mobile-ionic/src/pages/information/about/about.html, packages/carrier-mobile-ionic/src/pages/information/about/about.ts, packages/carrier-mobile-ionic/src/pages/information/terms-of-use/terms-of-use.ts, packages/common-angular/package.json, packages/common-angular/src/routers/user-router.service.ts, packages/common/package.json, packages/common/src/routers/IUserRouter.ts, packages/core/package.json, packages/core/res/templates/help/bg-BG.hbs, packages/core/res/templates/help/en-US.hbs, packages/core/res/templates/help/he-IL.hbs, packages/core/res/templates/help/ru-RU.hbs, packages/core/src/controllers/test.controller.ts, packages/core/src/services/users/UserCommandService.ts, packages/core/src/services/users/UsersService.ts, packages/merchant-tablet-ionic/src/pages/+info/+about/about.html, packages/merchant-tablet-ionic/src/pages/+info/+about/about.ts, packages/merchant-tablet-ionic/src/pages/+info/+terms-of-use/terms-of-use.ts, packages/shop-mobile-ionic/package.json, packages/shop-mobile-ionic/src/app/pages/+info/+about/about.page.html, packages/shop-mobile-ionic/src/app/pages/+info/+about/about.page.ts, packages/shop-mobile-ionic/src/app/pages/+info/+help/help.module.ts, packages/shop-mobile-ionic/src/app/pages/+info/+help/help.page.html, packages/shop-mobile-ionic/src/app/pages/+info/+help/help.page.ts, packages/shop-mobile-ionic/src/app/pages/+info/+privacy/privacy.page.html, packages/shop-mobile-ionic/src/app/pages/+info/+privacy/privacy.page.ts, packages/shop-mobile-ionic/src/app/pages/+info/+terms-of-use/terms-of-use.page.ts
=> feat: implemented functionality for help/about/privacy shopMobile

packages/admin-web-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/delivery-areas/warehouse-manage-tabs-delivery-areas.component.ts
---
#1276 
https://www.loom.com/share/77784c4277fe466996c955d18f1eecb7
=> fix: admin/store/manage store error

packages/merchant-tablet-ionic/src/pages/+track/track.ts
---
Issue: #1229 
https://www.loom.com/share/9543ad052b8c40dc9afdb547adf0cfed
@evereq
=> fix: track carrier search fix

packages/shop-mobile-ionic/src/app/components/menu/menu.component.html, packages/shop-mobile-ionic/src/app/components/menu/menu.component.ts, packages/shop-mobile-ionic/src/app/components/menu/menu.module.ts, packages/shop-mobile-ionic/src/app/components/menu/submenu/submenu.component.html, packages/shop-mobile-ionic/src/app/components/menu/submenu/submenu.component.scss, packages/shop-mobile-ionic/src/app/components/menu/submenu/submenu.component.ts, packages/shop-mobile-ionic/src/app/components/order/order.component.html, packages/shop-mobile-ionic/src/app/components/order/order.component.scss, packages/shop-mobile-ionic/src/app/components/order/order.component.ts, packages/shop-mobile-ionic/src/app/components/order/product/product.component.html, packages/shop-mobile-ionic/src/app/components/order/product/product.component.scss, packages/shop-mobile-ionic/src/app/components/order/product/product.component.ts, packages/shop-mobile-ionic/src/app/pages/+info/+about/about.page.html, packages/shop-mobile-ionic/src/app/pages/+info/+about/about.page.ts, packages/shop-mobile-ionic/src/app/pages/+info/+help/help.page.html, packages/shop-mobile-ionic/src/app/pages/+info/+help/help.page.ts, packages/shop-mobile-ionic/src/app/pages/+info/+privacy/privacy.page.html, packages/shop-mobile-ionic/src/app/pages/+info/+privacy/privacy.page.ts, packages/shop-mobile-ionic/src/app/pages/+info/+terms-of-use/terms-of-use.page.html, packages/shop-mobile-ionic/src/app/pages/+info/+terms-of-use/terms-of-use.page.ts, packages/shop-mobile-ionic/src/app/pages/+language/language.page.html, packages/shop-mobile-ionic/src/app/pages/+language/language.page.ts, packages/shop-mobile-ionic/src/app/pages/+orders-history/orders-history.page.html, packages/shop-mobile-ionic/src/app/pages/+orders-history/orders-history.page.ts, packages/shop-mobile-ionic/src/global.scss, packages/shop-mobile-ionic/src/index.html
---
Fixed Shop Mobile app to change direction on Hebrew language
https://www.loom.com/share/c73701fc7a8a4e0b8efe6c577fa744fd
=> fix: change app direction on hebrew

packages/carrier-mobile-ionic/src/pages/main/drive-to-warehouse/drive-to-warehouse.html, packages/carrier-mobile-ionic/src/pages/main/drive-to-warehouse/drive-to-warehouse.ts, packages/carrier-mobile-ionic/src/pages/main/main.html, packages/carrier-mobile-ionic/src/pages/main/main.ts, packages/carrier-mobile-ionic/src/pages/product/get-product/get-product.html, packages/carrier-mobile-ionic/src/pages/product/get-product/get-product.ts, packages/common-angular/src/routers/carrier-orders-router.service.ts, packages/core/src/services/carriers/CarriersOrdersService.ts
---
Issue: #1297 
Video: https://www.loom.com/share/007152a2a9a14533bd7c1543fd3c017c
When "Carrier Competition" is enabled - the first view with "take work" button is skipped.
=> fix: carriers can work on  same order

packages/admin-web-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/details/warehouse-manage-tabs-details.component.ts
---
Fixed error when entering Store -> Mange Store which blocked all store data to be populated properly
https://www.loom.com/share/03ed35383fd04aa297f31d8b0505e06d
=> fix: manage store error

packages/admin-web-angular/package.json, packages/admin-web-angular/src/app/@core/data/fakeDataServices/products.ts
---
Fixed fake data generator to continue seed when some images are not available
https://www.loom.com/share/c7fff8f0376b464886b129ad7f1e72f0
=> fix: fake data generator error

packages/admin-web-angular/src/app/@shared/warehouse/forms/warehouse-manage-tabs/details/warehouse-manage-tabs-details.component.ts
---
Fixed "Use specific carriers" option to be set to false and keep/show previously selected carriers if we set that option back to true.
https://www.loom.com/share/e6b6a119ec554792a5e4f9d85923445b
=> fix: set specific carriers to false and keep data

packages/shop-web-angular/src/app/+orders/orders.container.component.ts
---
Fixed error when navigating to Orders page on Shop Web app
https://www.loom.com/share/042f6caf0f3a4b70987bec4900888910
=> fix: shopweb orders page error

packages/admin-web-angular/src/app/@shared/product/forms/basic-info/basic-info-form.component.ts
=> feat: fix create product form

packages/shop-mobile-ionic/src/app/pages/+products/products-view/slides-view/slides-view.component.scss, packages/shop-web-angular/src/app/+login/byLocation/byLocation.component.scss, packages/shop-web-angular/src/app/+login/byLocation/location/location.component.scss, packages/shop-web-angular/src/app/shared/location-popup/location-popup.component.scss
=> feat: fix ng-deep

.github/workflows/codeql-analysis.yml, .github/workflows/docker-build-publish.yml
=> feat: add Github Actions (WIP)

.github/workflows/docker-build-publish.yml
=> feat: add all ever apps to docker builds
